// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: api/v1/model.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableColumn_Type int32

const (
	TableColumn_TYPE_UNSPECIFIED TableColumn_Type = 0
	TableColumn_TYPE_BOOL        TableColumn_Type = 1
	TableColumn_TYPE_DATE_TIME   TableColumn_Type = 2
	TableColumn_TYPE_INT64       TableColumn_Type = 3
	TableColumn_TYPE_REAL        TableColumn_Type = 4
	TableColumn_TYPE_STRING      TableColumn_Type = 5
	TableColumn_TYPE_TIMESPAN    TableColumn_Type = 6
)

// Enum value maps for TableColumn_Type.
var (
	TableColumn_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_BOOL",
		2: "TYPE_DATE_TIME",
		3: "TYPE_INT64",
		4: "TYPE_REAL",
		5: "TYPE_STRING",
		6: "TYPE_TIMESPAN",
	}
	TableColumn_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_BOOL":        1,
		"TYPE_DATE_TIME":   2,
		"TYPE_INT64":       3,
		"TYPE_REAL":        4,
		"TYPE_STRING":      5,
		"TYPE_TIMESPAN":    6,
	}
)

func (x TableColumn_Type) Enum() *TableColumn_Type {
	p := new(TableColumn_Type)
	*p = x
	return p
}

func (x TableColumn_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableColumn_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_model_proto_enumTypes[0].Descriptor()
}

func (TableColumn_Type) Type() protoreflect.EnumType {
	return &file_api_v1_model_proto_enumTypes[0]
}

func (x TableColumn_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableColumn_Type.Descriptor instead.
func (TableColumn_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_model_proto_rawDescGZIP(), []int{3, 0}
}

type TableSchema_Type int32

const (
	TableSchema_TYPE_UNSPECIFIED TableSchema_Type = 0
	TableSchema_TYPE_RAW         TableSchema_Type = 1
	TableSchema_TYPE_PARSED      TableSchema_Type = 2
)

// Enum value maps for TableSchema_Type.
var (
	TableSchema_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_RAW",
		2: "TYPE_PARSED",
	}
	TableSchema_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_RAW":         1,
		"TYPE_PARSED":      2,
	}
)

func (x TableSchema_Type) Enum() *TableSchema_Type {
	p := new(TableSchema_Type)
	*p = x
	return p
}

func (x TableSchema_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableSchema_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_model_proto_enumTypes[1].Descriptor()
}

func (TableSchema_Type) Type() protoreflect.EnumType {
	return &file_api_v1_model_proto_enumTypes[1]
}

func (x TableSchema_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableSchema_Type.Descriptor instead.
func (TableSchema_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_model_proto_rawDescGZIP(), []int{4, 0}
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id - id of the session.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// tables - tables in the session.
	Tables []*TableSchema `protobuf:"bytes,2,rep,name=tables,proto3" json:"tables,omitempty"`
	// name - display name of the session.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetTables() []*TableSchema {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TableKeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// key - key of the table column.
	Key           string                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueBool     *wrapperspb.BoolValue   `protobuf:"bytes,3,opt,name=value_bool,json=valueBool,proto3" json:"value_bool,omitempty"`
	ValueDateTime *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=value_date_time,json=valueDateTime,proto3" json:"value_date_time,omitempty"`
	ValueInt64    *wrapperspb.Int64Value  `protobuf:"bytes,5,opt,name=value_int64,json=valueInt64,proto3" json:"value_int64,omitempty"`
	ValueReal     *wrapperspb.DoubleValue `protobuf:"bytes,6,opt,name=value_real,json=valueReal,proto3" json:"value_real,omitempty"`
	ValueString   *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=value_string,json=valueString,proto3" json:"value_string,omitempty"`
	ValueDuration *durationpb.Duration    `protobuf:"bytes,8,opt,name=value_duration,json=valueDuration,proto3" json:"value_duration,omitempty"`
}

func (x *TableKeyValue) Reset() {
	*x = TableKeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableKeyValue) ProtoMessage() {}

func (x *TableKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableKeyValue.ProtoReflect.Descriptor instead.
func (*TableKeyValue) Descriptor() ([]byte, []int) {
	return file_api_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *TableKeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TableKeyValue) GetValueBool() *wrapperspb.BoolValue {
	if x != nil {
		return x.ValueBool
	}
	return nil
}

func (x *TableKeyValue) GetValueDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ValueDateTime
	}
	return nil
}

func (x *TableKeyValue) GetValueInt64() *wrapperspb.Int64Value {
	if x != nil {
		return x.ValueInt64
	}
	return nil
}

func (x *TableKeyValue) GetValueReal() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ValueReal
	}
	return nil
}

func (x *TableKeyValue) GetValueString() *wrapperspb.StringValue {
	if x != nil {
		return x.ValueString
	}
	return nil
}

func (x *TableKeyValue) GetValueDuration() *durationpb.Duration {
	if x != nil {
		return x.ValueDuration
	}
	return nil
}

type TableRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Columns []*TableKeyValue `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
}

func (x *TableRow) Reset() {
	*x = TableRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRow) ProtoMessage() {}

func (x *TableRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRow.ProtoReflect.Descriptor instead.
func (*TableRow) Descriptor() ([]byte, []int) {
	return file_api_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *TableRow) GetColumns() []*TableKeyValue {
	if x != nil {
		return x.Columns
	}
	return nil
}

type TableColumn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// key - key of the table column.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// type - type of the table column.
	Type TableColumn_Type `protobuf:"varint,2,opt,name=type,proto3,enum=api.v1.TableColumn_Type" json:"type,omitempty"`
}

func (x *TableColumn) Reset() {
	*x = TableColumn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableColumn) ProtoMessage() {}

func (x *TableColumn) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableColumn.ProtoReflect.Descriptor instead.
func (*TableColumn) Descriptor() ([]byte, []int) {
	return file_api_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *TableColumn) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TableColumn) GetType() TableColumn_Type {
	if x != nil {
		return x.Type
	}
	return TableColumn_TYPE_UNSPECIFIED
}

type TableSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name - name of the table.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type - type of the table.
	Type TableSchema_Type `protobuf:"varint,2,opt,name=type,proto3,enum=api.v1.TableSchema_Type" json:"type,omitempty"`
	// columns - columns of the table.
	Columns []*TableColumn `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	// session_id - the session id of the table.
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *TableSchema) Reset() {
	*x = TableSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSchema) ProtoMessage() {}

func (x *TableSchema) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSchema.ProtoReflect.Descriptor instead.
func (*TableSchema) Descriptor() ([]byte, []int) {
	return file_api_v1_model_proto_rawDescGZIP(), []int{4}
}

func (x *TableSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableSchema) GetType() TableSchema_Type {
	if x != nil {
		return x.Type
	}
	return TableSchema_TYPE_UNSPECIFIED
}

func (x *TableSchema) GetColumns() []*TableColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *TableSchema) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_api_v1_model_proto protoreflect.FileDescriptor

var file_api_v1_model_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a,
	0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x06, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x06, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x9e, 0x03, 0x0a, 0x0d, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x39, 0x0a,
	0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x42, 0x0a, 0x0f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x0b,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0a,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x3b, 0x0a, 0x0a, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x12, 0x3f, 0x0a, 0x0c, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0b, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x40, 0x0a, 0x0e, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a, 0x08, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x6f, 0x77, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x22, 0xd2, 0x01, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42,
	0x4f, 0x4f, 0x4c, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x41,
	0x54, 0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x52, 0x45, 0x41, 0x4c, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x50, 0x41, 0x4e, 0x10, 0x06, 0x22, 0xda, 0x01, 0x0a,
	0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2d,
	0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x52, 0x41, 0x57, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x50, 0x41, 0x52, 0x53, 0x45, 0x44, 0x10, 0x02, 0x42, 0x08, 0x5a, 0x06, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_model_proto_rawDescOnce sync.Once
	file_api_v1_model_proto_rawDescData = file_api_v1_model_proto_rawDesc
)

func file_api_v1_model_proto_rawDescGZIP() []byte {
	file_api_v1_model_proto_rawDescOnce.Do(func() {
		file_api_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_model_proto_rawDescData)
	})
	return file_api_v1_model_proto_rawDescData
}

var file_api_v1_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_model_proto_goTypes = []interface{}{
	(TableColumn_Type)(0),          // 0: api.v1.TableColumn.Type
	(TableSchema_Type)(0),          // 1: api.v1.TableSchema.Type
	(*Session)(nil),                // 2: api.v1.Session
	(*TableKeyValue)(nil),          // 3: api.v1.TableKeyValue
	(*TableRow)(nil),               // 4: api.v1.TableRow
	(*TableColumn)(nil),            // 5: api.v1.TableColumn
	(*TableSchema)(nil),            // 6: api.v1.TableSchema
	(*wrapperspb.BoolValue)(nil),   // 7: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*wrapperspb.Int64Value)(nil),  // 9: google.protobuf.Int64Value
	(*wrapperspb.DoubleValue)(nil), // 10: google.protobuf.DoubleValue
	(*wrapperspb.StringValue)(nil), // 11: google.protobuf.StringValue
	(*durationpb.Duration)(nil),    // 12: google.protobuf.Duration
}
var file_api_v1_model_proto_depIdxs = []int32{
	6,  // 0: api.v1.Session.tables:type_name -> api.v1.TableSchema
	7,  // 1: api.v1.TableKeyValue.value_bool:type_name -> google.protobuf.BoolValue
	8,  // 2: api.v1.TableKeyValue.value_date_time:type_name -> google.protobuf.Timestamp
	9,  // 3: api.v1.TableKeyValue.value_int64:type_name -> google.protobuf.Int64Value
	10, // 4: api.v1.TableKeyValue.value_real:type_name -> google.protobuf.DoubleValue
	11, // 5: api.v1.TableKeyValue.value_string:type_name -> google.protobuf.StringValue
	12, // 6: api.v1.TableKeyValue.value_duration:type_name -> google.protobuf.Duration
	3,  // 7: api.v1.TableRow.columns:type_name -> api.v1.TableKeyValue
	0,  // 8: api.v1.TableColumn.type:type_name -> api.v1.TableColumn.Type
	1,  // 9: api.v1.TableSchema.type:type_name -> api.v1.TableSchema.Type
	5,  // 10: api.v1.TableSchema.columns:type_name -> api.v1.TableColumn
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_v1_model_proto_init() }
func file_api_v1_model_proto_init() {
	if File_api_v1_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableKeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableColumn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_model_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_model_proto_goTypes,
		DependencyIndexes: file_api_v1_model_proto_depIdxs,
		EnumInfos:         file_api_v1_model_proto_enumTypes,
		MessageInfos:      file_api_v1_model_proto_msgTypes,
	}.Build()
	File_api_v1_model_proto = out.File
	file_api_v1_model_proto_rawDesc = nil
	file_api_v1_model_proto_goTypes = nil
	file_api_v1_model_proto_depIdxs = nil
}
