// @generated by protobuf-ts 2.7.0
// @generated from protobuf file "api/v1/model.proto" (package "api.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// sessions -(many)-> tables

/**
 * @generated from protobuf message api.v1.Session
 */
export interface Session {
    /**
     * id - id of the session.
     *
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * tables - tables in the session.
     *
     * @generated from protobuf field: repeated api.v1.TableSchema tables = 2;
     */
    tables: TableSchema[];
}
/**
 * @generated from protobuf message api.v1.TableQuery
 */
export interface TableQuery {
    /**
     * table - name of the table to query.
     *
     * @generated from protobuf field: string table = 1;
     */
    table: string;
    /**
     * columns - columns to return.
     *
     * @generated from protobuf field: repeated string columns = 2;
     */
    columns: string[];
    /**
     * where_clauses - where clause to filter results.
     *
     * @generated from protobuf field: repeated string where_clauses = 3;
     */
    whereClauses: string[];
    /**
     * order_by_clauses - order by clause.
     *
     * @generated from protobuf field: repeated string order_by_clauses = 4;
     */
    orderByClauses: string[];
}
/**
 * @generated from protobuf message api.v1.TableKeyValue
 */
export interface TableKeyValue {
    /**
     * key - key of the table column.
     *
     * @generated from protobuf field: string key = 1;
     */
    key: string;
    /**
     * value - value of the table column.
     *
     * @generated from protobuf field: bytes value = 2;
     */
    value: Uint8Array;
}
/**
 * @generated from protobuf message api.v1.TableRow
 */
export interface TableRow {
    /**
     * @generated from protobuf field: repeated api.v1.TableKeyValue columns = 1;
     */
    columns: TableKeyValue[];
}
/**
 * @generated from protobuf message api.v1.TableColumn
 */
export interface TableColumn {
    /**
     * key - key of the table column.
     *
     * @generated from protobuf field: string key = 1;
     */
    key: string;
    /**
     * type - type of the table column.
     *
     * @generated from protobuf field: api.v1.TableColumn.Type type = 2;
     */
    type: TableColumn_Type;
}
/**
 * @generated from protobuf enum api.v1.TableColumn.Type
 */
export enum TableColumn_Type {
    /**
     * @generated from protobuf enum value: TYPE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TYPE_BOOL = 1;
     */
    BOOL = 1,
    /**
     * @generated from protobuf enum value: TYPE_DATE_TIME = 2;
     */
    DATE_TIME = 2,
    /**
     * @generated from protobuf enum value: TYPE_INT64 = 3;
     */
    INT64 = 3,
    /**
     * @generated from protobuf enum value: TYPE_REAL = 4;
     */
    REAL = 4,
    /**
     * @generated from protobuf enum value: TYPE_STRING = 5;
     */
    STRING = 5,
    /**
     * @generated from protobuf enum value: TYPE_TIMESPAN = 6;
     */
    TIMESPAN = 6
}
/**
 * @generated from protobuf message api.v1.TableSchema
 */
export interface TableSchema {
    /**
     * name - name of the table.
     *
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * type - type of the table.
     *
     * @generated from protobuf field: api.v1.TableSchema.Type type = 2;
     */
    type: TableSchema_Type;
    /**
     * columns - columns of the table.
     *
     * @generated from protobuf field: repeated api.v1.TableColumn columns = 3;
     */
    columns: TableColumn[];
    /**
     * session_id - the session id of the table.
     *
     * @generated from protobuf field: string session_id = 4;
     */
    sessionId: string;
}
/**
 * @generated from protobuf enum api.v1.TableSchema.Type
 */
export enum TableSchema_Type {
    /**
     * @generated from protobuf enum value: TYPE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TYPE_RAW = 1;
     */
    RAW = 1,
    /**
     * @generated from protobuf enum value: TYPE_PARSED = 2;
     */
    PARSED = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class Session$Type extends MessageType<Session> {
    constructor() {
        super("api.v1.Session", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tables", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TableSchema }
        ]);
    }
    create(value?: PartialMessage<Session>): Session {
        const message = { id: "", tables: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Session>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Session): Session {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* repeated api.v1.TableSchema tables */ 2:
                    message.tables.push(TableSchema.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Session, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* repeated api.v1.TableSchema tables = 2; */
        for (let i = 0; i < message.tables.length; i++)
            TableSchema.internalBinaryWrite(message.tables[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.v1.Session
 */
export const Session = new Session$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TableQuery$Type extends MessageType<TableQuery> {
    constructor() {
        super("api.v1.TableQuery", [
            { no: 1, name: "table", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "columns", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "where_clauses", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "order_by_clauses", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TableQuery>): TableQuery {
        const message = { table: "", columns: [], whereClauses: [], orderByClauses: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TableQuery>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TableQuery): TableQuery {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string table */ 1:
                    message.table = reader.string();
                    break;
                case /* repeated string columns */ 2:
                    message.columns.push(reader.string());
                    break;
                case /* repeated string where_clauses */ 3:
                    message.whereClauses.push(reader.string());
                    break;
                case /* repeated string order_by_clauses */ 4:
                    message.orderByClauses.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TableQuery, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string table = 1; */
        if (message.table !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.table);
        /* repeated string columns = 2; */
        for (let i = 0; i < message.columns.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.columns[i]);
        /* repeated string where_clauses = 3; */
        for (let i = 0; i < message.whereClauses.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.whereClauses[i]);
        /* repeated string order_by_clauses = 4; */
        for (let i = 0; i < message.orderByClauses.length; i++)
            writer.tag(4, WireType.LengthDelimited).string(message.orderByClauses[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.v1.TableQuery
 */
export const TableQuery = new TableQuery$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TableKeyValue$Type extends MessageType<TableKeyValue> {
    constructor() {
        super("api.v1.TableKeyValue", [
            { no: 1, name: "key", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "value", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<TableKeyValue>): TableKeyValue {
        const message = { key: "", value: new Uint8Array(0) };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TableKeyValue>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TableKeyValue): TableKeyValue {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string key */ 1:
                    message.key = reader.string();
                    break;
                case /* bytes value */ 2:
                    message.value = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TableKeyValue, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string key = 1; */
        if (message.key !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.key);
        /* bytes value = 2; */
        if (message.value.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.value);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.v1.TableKeyValue
 */
export const TableKeyValue = new TableKeyValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TableRow$Type extends MessageType<TableRow> {
    constructor() {
        super("api.v1.TableRow", [
            { no: 1, name: "columns", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TableKeyValue }
        ]);
    }
    create(value?: PartialMessage<TableRow>): TableRow {
        const message = { columns: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TableRow>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TableRow): TableRow {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated api.v1.TableKeyValue columns */ 1:
                    message.columns.push(TableKeyValue.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TableRow, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated api.v1.TableKeyValue columns = 1; */
        for (let i = 0; i < message.columns.length; i++)
            TableKeyValue.internalBinaryWrite(message.columns[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.v1.TableRow
 */
export const TableRow = new TableRow$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TableColumn$Type extends MessageType<TableColumn> {
    constructor() {
        super("api.v1.TableColumn", [
            { no: 1, name: "key", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["api.v1.TableColumn.Type", TableColumn_Type, "TYPE_"] }
        ]);
    }
    create(value?: PartialMessage<TableColumn>): TableColumn {
        const message = { key: "", type: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TableColumn>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TableColumn): TableColumn {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string key */ 1:
                    message.key = reader.string();
                    break;
                case /* api.v1.TableColumn.Type type */ 2:
                    message.type = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TableColumn, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string key = 1; */
        if (message.key !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.key);
        /* api.v1.TableColumn.Type type = 2; */
        if (message.type !== 0)
            writer.tag(2, WireType.Varint).int32(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.v1.TableColumn
 */
export const TableColumn = new TableColumn$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TableSchema$Type extends MessageType<TableSchema> {
    constructor() {
        super("api.v1.TableSchema", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["api.v1.TableSchema.Type", TableSchema_Type, "TYPE_"] },
            { no: 3, name: "columns", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TableColumn },
            { no: 4, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TableSchema>): TableSchema {
        const message = { name: "", type: 0, columns: [], sessionId: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TableSchema>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TableSchema): TableSchema {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* api.v1.TableSchema.Type type */ 2:
                    message.type = reader.int32();
                    break;
                case /* repeated api.v1.TableColumn columns */ 3:
                    message.columns.push(TableColumn.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string session_id */ 4:
                    message.sessionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TableSchema, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* api.v1.TableSchema.Type type = 2; */
        if (message.type !== 0)
            writer.tag(2, WireType.Varint).int32(message.type);
        /* repeated api.v1.TableColumn columns = 3; */
        for (let i = 0; i < message.columns.length; i++)
            TableColumn.internalBinaryWrite(message.columns[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* string session_id = 4; */
        if (message.sessionId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.sessionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.v1.TableSchema
 */
export const TableSchema = new TableSchema$Type();
